kind: ConfigMap
apiVersion: v1
metadata:
  name: yoke-attender
  namespace: yoke-network
  selfLink: /api/v1/namespaces/yoke-network/configmaps/yoke-attender
  uid: 7a6986e8-a0fd-4e0c-bed6-83d33c54d6dd
  resourceVersion: '2239203'
  creationTimestamp: '2021-02-11T20:07:32Z'
  managedFields:
    - manager: kubectl
      operation: Update
      apiVersion: v1
      time: '2021-02-11T20:07:32Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          .: {}
          'f:application-container.yml': {}
data:
  application-container.yml: |+
    spring:
      cloud:
        stream:
          bindings:
            addEventAttender:
              destination: yoke-add-event-attender          
              producer:
                partition-count: 3
            deleteEventAttender:
              destination: yoke-delete-event-attender
              producer:
                partition-count: 3
          kafka:
            binder:
              brokers: yoke-kafka:9092
              autoAddPartitions: true
      jpa:
        database: POSTGRESQL
        show-sql: true
        generate-ddl: true
        hibernate:
          ddl-auto: create
      datasource:
        platform: postgres
        url: jdbc:postgresql://postgres:5432/postgres
        username: postgres
        password: ${POSTGRES_PASSWORD}
      zipkin:
        baseUrl: http://yoke-zipkin:9411

    logback:
      destination:
        url: logstash
        port: 5000
    yoke:
      notify:
        url: http://yoke-notify/event

